/*
 * SeniorFight.java
 *
 * Created on __DATE__, __TIME__
 */

package UI;

import action.UIFunc;

/**
 *
 * @author  __USER__
 */
public class SeniorFight extends javax.swing.JFrame {

	/** Creates new form SeniorFight */
	public SeniorFight() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jCheckBoxUseLanAnswer = new javax.swing.JCheckBox();
		jPanelLanAnswer = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldServerIP = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldFaqSendPort = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldHoursStart = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldHoursEnd = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jCheckBoxLanIpIsOnline = new javax.swing.JCheckBox();
		jLabel9 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jCheckBoxAutoXiuLi = new javax.swing.JCheckBox();
		jPanelUseRepair = new javax.swing.JPanel();
		jCheckBoxAutoEmptyParcel = new javax.swing.JCheckBox();
		jCheckBoxXiuLi_UseMenPai = new javax.swing.JCheckBox();

		setTitle("\u9ad8\u7ea7\u6253\u602a\u6a21\u5f0f");

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u5c40\u57df\u7f51\u7b54\u9898"));

		jCheckBoxUseLanAnswer
				.setText("\u662f\u5426\u5f00\u542f\u5c40\u57df\u7f51\u7b54\u9898");
		jCheckBoxUseLanAnswer
				.addItemListener(new java.awt.event.ItemListener() {
					public void itemStateChanged(java.awt.event.ItemEvent evt) {
						jCheckBoxUseLanAnswerItemStateChanged(evt);
					}
				});

		jLabel1
				.setText("\u6307\u5b9a\u7684\u7b54\u9898\u7535\u8111\u5c40\u57df\u7f51IP\u5730\u5740\uff0c\u591a\u4e2a\u7528|\u5206\u5272\uff1a");

		jTextFieldServerIP.setText("192.168.0.101|192.168.0.102");

		jLabel2
				.setText("\u7b54\u9898\u7535\u8111\u5f00\u653e\u7684\u7aef\u53e3\uff08\u4f7f\u7528\u9ed8\u8ba4\u5373\u53ef\uff09\uff1a");

		jTextFieldFaqSendPort.setText("12345");

		jLabel3.setText("\u6bcf\u5929\u5f00\u542f\u65f6\u95f4\uff1a");

		jLabel4.setText("\u65f6\u5230");

		jLabel7.setText("\u65f6");

		jCheckBoxLanIpIsOnline
				.setText("\u667a\u80fd\u5224\u65ad\u6b64IP\u662f\u5426\u5728\u7ebf");
		jCheckBoxLanIpIsOnline
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseEntered(java.awt.event.MouseEvent evt) {
						jCheckBoxLanIpIsOnlineMouseEntered(evt);
					}

					public void mouseExited(java.awt.event.MouseEvent evt) {
						jCheckBoxLanIpIsOnlineMouseExited(evt);
					}
				});

		jLabel9
				.setText("\u65f6\u95f4\u4e3a24\u5c0f\u65f6\u5236\uff0c\u5982\u586b8\u523016\uff0c\u5219\u4ece8\u70b9\u5f00\u59cb\u5230\u4e0b\u534815\u70b959\u5206\u7ed3\u675f");

		javax.swing.GroupLayout jPanelLanAnswerLayout = new javax.swing.GroupLayout(
				jPanelLanAnswer);
		jPanelLanAnswer.setLayout(jPanelLanAnswerLayout);
		jPanelLanAnswerLayout
				.setHorizontalGroup(jPanelLanAnswerLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelLanAnswerLayout
										.createSequentialGroup()
										.addGroup(
												jPanelLanAnswerLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelLanAnswerLayout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelLanAnswerLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								343,
																								Short.MAX_VALUE)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanelLanAnswerLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												jLabel2,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												jPanelLanAnswerLayout
																														.createSequentialGroup()
																														.addComponent(
																																jLabel3)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jTextFieldHoursStart,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																49,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jLabel4,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																45,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jTextFieldHoursEnd,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																49,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jLabel7,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																31,
																																javax.swing.GroupLayout.PREFERRED_SIZE))))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanelLanAnswerLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextFieldFaqSendPort,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								282,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextFieldServerIP,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								282,
																								Short.MAX_VALUE)
																						.addComponent(
																								jCheckBoxLanIpIsOnline,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								244,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																631,
																Short.MAX_VALUE))
										.addGap(30, 30, 30)));
		jPanelLanAnswerLayout
				.setVerticalGroup(jPanelLanAnswerLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelLanAnswerLayout
										.createSequentialGroup()
										.addGroup(
												jPanelLanAnswerLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextFieldServerIP,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanelLanAnswerLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextFieldFaqSendPort,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanelLanAnswerLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jTextFieldHoursStart,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																jTextFieldHoursEnd,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																jCheckBoxLanIpIsOnline))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel9)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGroup(
						jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jCheckBoxUseLanAnswer,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										188,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jPanelLanAnswer,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(
						jCheckBoxUseLanAnswer).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanelLanAnswer,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u6253\u602a\u8bbe\u7f6e"));

		jCheckBoxAutoXiuLi
				.setText("\u662f\u5426\u5f00\u542f\u81ea\u52a8\u4fee\u7406\u88c5\u5907");
		jCheckBoxAutoXiuLi.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jCheckBoxAutoXiuLiItemStateChanged(evt);
			}
		});
		jCheckBoxAutoXiuLi
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxAutoXiuLiActionPerformed(evt);
					}
				});

		jCheckBoxAutoEmptyParcel
				.setText("\u4fee\u7406\u88c5\u5907\u65f6\u662f\u5426\u81ea\u52a8\u5356\u51fa\u6e05\u7a7a\u5305\u88f9");

		jCheckBoxXiuLi_UseMenPai
				.setText("\u662f\u5426\u6709\u95e8\u6d3e(\u4e0d\u9009\u5219\u4f7f\u7528\u5730\u56fe\u5185\u94c1\u5320)");

		javax.swing.GroupLayout jPanelUseRepairLayout = new javax.swing.GroupLayout(
				jPanelUseRepair);
		jPanelUseRepair.setLayout(jPanelUseRepairLayout);
		jPanelUseRepairLayout
				.setHorizontalGroup(jPanelUseRepairLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelUseRepairLayout
										.createSequentialGroup()
										.addGap(5, 5, 5)
										.addComponent(
												jCheckBoxAutoEmptyParcel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												303,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jCheckBoxXiuLi_UseMenPai,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												288, Short.MAX_VALUE).addGap(
												49, 49, 49)));
		jPanelUseRepairLayout
				.setVerticalGroup(jPanelUseRepairLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelUseRepairLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelUseRepairLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBoxAutoEmptyParcel)
														.addComponent(
																jCheckBoxXiuLi_UseMenPai))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanelUseRepair,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jCheckBoxAutoXiuLi,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																271,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addComponent(
						jCheckBoxAutoXiuLi).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanelUseRepair,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												208,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jCheckBoxLanIpIsOnlineMouseExited(java.awt.event.MouseEvent evt) {
		new UIFunc().hiddenMessage();
	}

	private void jCheckBoxLanIpIsOnlineMouseEntered(
			java.awt.event.MouseEvent evt) {
		new UIFunc().showMessage(evt.getXOnScreen() + 10,
				evt.getYOnScreen() + 10, 300, 200,
				"使用时先判断答题的电脑是否在线，若是在线则使用局域网答题，若是不在线使用信诺远程代答");
	}

	private void jCheckBoxUseLanAnswerItemStateChanged(
			java.awt.event.ItemEvent evt) {
		new UIFunc().jPanelLanAnswer();
	}

	private void jCheckBoxAutoXiuLiItemStateChanged(java.awt.event.ItemEvent evt) {
		new UIFunc().autoXiuLiItemStateChanged();
	}

	private void jCheckBoxAutoXiuLiActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SeniorFight().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public static javax.swing.JCheckBox jCheckBoxAutoEmptyParcel;
	public static javax.swing.JCheckBox jCheckBoxAutoXiuLi;
	public static javax.swing.JCheckBox jCheckBoxLanIpIsOnline;
	public static javax.swing.JCheckBox jCheckBoxUseLanAnswer;
	public static javax.swing.JCheckBox jCheckBoxXiuLi_UseMenPai;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	public static javax.swing.JPanel jPanelLanAnswer;
	public static javax.swing.JPanel jPanelUseRepair;
	public static javax.swing.JTextField jTextFieldFaqSendPort;
	public static javax.swing.JTextField jTextFieldHoursEnd;
	public static javax.swing.JTextField jTextFieldHoursStart;
	public static javax.swing.JTextField jTextFieldServerIP;
	// End of variables declaration//GEN-END:variables

}